---

# - name: Add the Linux OS specific varibles
#   include_vars: linux.yml

- name: Gather package facts for linux
  set_fact:
    package_info: "{{ packages_by_pull[golang_version][ansible_architecture] }}"

- name: Download package for linux
  get_url:
    url: "{{ package_info.url }}"
    dest: "{{ temp_dir }}"

- name: Install golang for linux
  unarchive: 
    src: "{{ temp_dir }}/{{ package_info.package }}"
    dest: "{{ install_dir }}"
    copy: no

- name: Remove install package for linux
  file: path={{ temp_dir }}/{{ package_info.package }} state=absent

- name: Do common something for linux
  include: linux-common.yml
