---
# tasks file for golang

- name: Check whether golang is already installed
  command: "go version"
  failed_when: false
  changed_when: false
  register: version_check_result

- set_fact:
    golang_is_installed: "{{ version_check_result.rc == 0 }}"

- block:

    - name: Install golang for linux
      include: linux.yml
      when: ansible_os_family!="Windows"
    
    - name: Install golang for window
      include: window.yml
      when: ansible_os_family=="Windows"

  when: not golang_is_installed
