---
# tasks file for golang

- name: Install golang for linux
  include: linux.yml
  when: ansible_os_family!="Windows"

- name: Install golang for window
  include: window.yml
  when: ansible_os_family=="Windows"

# - name: Check whether golang is already installed for linux
#   command: "go version"
#   failed_when: false
#   changed_when: false
#   register: version_check_result
#   when: ansible_os_family!="Windows"


# - name: Check whether golang is already installed for window
#   win_command: "go version"
#   failed_when: false
#   changed_when: false
#   register: version_check_result
#   when: ansible_os_family=="Windows"


# - set_fact:
#     golang_is_installed: "{{ version_check_result.rc == 0 }}"


# - debug: var=golang_is_installed

# - block:
#   - name: Install golang for linux by {{ mode }}
#     include: "linux-{{ mode }}.yml"
#     when: ansible_os_family!="Windows"

#   - name: Install golang for window by {{ mode }}
#     include: "window-{{ mode }}.yml"
#     when: ansible_os_family=="Windows"
#   when: not golang_is_installed

# - block:
#     - name: Offline install golang for linux
#       include: push/linux.yml
#       when: ansible_os_family!="Windows"

#     - name: Offline install golang for window
#       include: push/window.yml
#       when: ansible_os_family=="Windows"
#   when: not golang_is_installed and push
