---
# tasks file for golang

- name: Check whether golang is already installed
  command: "go version"
  failed_when: false
  changed_when: false
  register: version_check_result

- set_fact:
    golang_is_installed: "{{ version_check_result.rc == 0 }}"

- block:
  - name: Online install golang for linux
    include: online/linux.yml
    when: ansible_os_family!="Windows"

  - name: Online install golang for window
    include: online/window.yml
    when: ansible_os_family=="Windows"
  when: not golang_is_installed and not offline

- block:
    - name: Offline install golang for linux
      include: offline/linux.yml
      when: ansible_os_family!="Windows"

    - name: Offline install golang for window
      include: offline/window.yml
      when: ansible_os_family=="Windows"
  when: not golang_is_installed and offline
