---

- name: debug user info
  debug:
    var: user is defined

- block:
   - set_fact: group={{ user }}
     when: group is not undefined

   - name: Add a group 
     group: name={{ group }}
   
   - name: Add a user
     user: name={{ user }} group={{ group }}
  when: user is defined