---

- name: Gather package facts for window
  set_fact:
    package_info: "{{ packages_by_push[golang_version][ansible_architecture] }}"

- name: Check and create install and temp directory for window
  win_file: path={{ item }} state=directory
  with_items:
    - "{{ install_dir }}"
    - "{{ temp_dir }}"
    # - "{{ workspace_dir }}"


- name: Copy a install package for window
  win_copy: src={{ package_info.path }} dest={{ temp_dir }}

- name: Do common something for window
  include: window-common.yml
